[package]
name = "choreo_core"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = {version = "1.0.217", features = ["derive"]}
serde_json = { workspace = true }
serde_yaml = { workspace = true }
choreo_meta = { workspace = true }
thiserror = {workspace = true }